// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaCitas.Data;

#nullable disable

namespace SistemaCitas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920031009_InitDB1")]
    partial class InitDB1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("ROL", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("ROL_CLAIM", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("USUARIO_CLAIM", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("USUARIO_LOGIN", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("USUARIO_ROL", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("USUARIO_TOKEN", (string)null);
                });

            modelBuilder.Entity("SistemaCitas.Models.AtencionDiagnostico", b =>
                {
                    b.Property<int>("IdAtencion")
                        .HasColumnType("int");

                    b.Property<string>("CodigoCie10")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("TipoDiagnostico")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("IdAtencion", "CodigoCie10");

                    b.HasIndex("CodigoCie10");

                    b.ToTable("ATENCION_DIAGNOSTICO");
                });

            modelBuilder.Entity("SistemaCitas.Models.AtencionMedica", b =>
                {
                    b.Property<int>("IdAtencion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAtencion"));

                    b.Property<DateTime>("FechaHoraAtencion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCita")
                        .HasColumnType("int");

                    b.Property<string>("MotivoConsulta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Sintomatologia")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdAtencion");

                    b.HasIndex("IdCita")
                        .IsUnique();

                    b.ToTable("ATENCION_MEDICA");
                });

            modelBuilder.Entity("SistemaCitas.Models.Auditoria", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAuditoria"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ClaveRegistro")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ValorAnterior")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ValorNuevo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AUDITORIA");
                });

            modelBuilder.Entity("SistemaCitas.Models.Cie10", b =>
                {
                    b.Property<string>("CodigoCie10")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CodigoCie10");

                    b.ToTable("CIE10");

                    b.HasData(
                        new
                        {
                            CodigoCie10 = "J00",
                            Descripcion = "Rinofaringitis aguda (resfriado comun)"
                        },
                        new
                        {
                            CodigoCie10 = "E11",
                            Descripcion = "Diabetes mellitus tipo 2"
                        },
                        new
                        {
                            CodigoCie10 = "I10",
                            Descripcion = "Hipertension esencial (primaria)"
                        });
                });

            modelBuilder.Entity("SistemaCitas.Models.Cita", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCita"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateOnly>("FechaCita")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("HoraCita")
                        .HasColumnType("time");

                    b.Property<DateTime?>("HoraLlegada")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDoctor")
                        .HasColumnType("int");

                    b.Property<int>("IdIpress")
                        .HasColumnType("int");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<decimal>("PuntajeAlAgendar")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdCita");

                    b.HasIndex("IdIpress");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("IdDoctor", "FechaCita", "HoraCita")
                        .IsUnique();

                    b.ToTable("CITA");
                });

            modelBuilder.Entity("SistemaCitas.Models.Departamento", b =>
                {
                    b.Property<string>("IdDepartamento")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IdDepartamento");

                    b.ToTable("DEPARTAMENTO");

                    b.HasData(
                        new
                        {
                            IdDepartamento = "13",
                            Nombre = "La Libertad"
                        });
                });

            modelBuilder.Entity("SistemaCitas.Models.DetalleReceta", b =>
                {
                    b.Property<int>("IdDetalleReceta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleReceta"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdAtencion")
                        .HasColumnType("int");

                    b.Property<int>("IdMedicamento")
                        .HasColumnType("int");

                    b.Property<string>("Indicaciones")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdDetalleReceta");

                    b.HasIndex("IdAtencion");

                    b.HasIndex("IdMedicamento");

                    b.ToTable("DETALLE_RECETA");
                });

            modelBuilder.Entity("SistemaCitas.Models.Distrito", b =>
                {
                    b.Property<string>("IdDistrito")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("IdProvincia")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IdDistrito");

                    b.HasIndex("IdProvincia", "Nombre")
                        .IsUnique();

                    b.ToTable("DISTRITO");

                    b.HasData(
                        new
                        {
                            IdDistrito = "130101",
                            IdProvincia = "1301",
                            Nombre = "Trujillo"
                        },
                        new
                        {
                            IdDistrito = "130104",
                            IdProvincia = "1301",
                            Nombre = "Laredo"
                        },
                        new
                        {
                            IdDistrito = "130105",
                            IdProvincia = "1301",
                            Nombre = "Moche"
                        },
                        new
                        {
                            IdDistrito = "130109",
                            IdProvincia = "1301",
                            Nombre = "Huanchaco"
                        });
                });

            modelBuilder.Entity("SistemaCitas.Models.Doctor", b =>
                {
                    b.Property<int>("IdDoctor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDoctor"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Cmp")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("EstadoHabilitacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaValidacionCmp")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdIpress")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoContrato")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdDoctor");

                    b.HasIndex("Cmp")
                        .IsUnique();

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("IdIpress");

                    b.HasIndex("IdTipoContrato");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasFilter("[UsuarioId] IS NOT NULL");

                    b.ToTable("DOCTOR");
                });

            modelBuilder.Entity("SistemaCitas.Models.DoctorEspecialidad", b =>
                {
                    b.Property<int>("IdDoctor")
                        .HasColumnType("int");

                    b.Property<int>("IdEspecialidad")
                        .HasColumnType("int");

                    b.Property<string>("Rne")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdDoctor", "IdEspecialidad");

                    b.HasIndex("IdEspecialidad");

                    b.ToTable("DOCTOR_ESPECIALIDAD");
                });

            modelBuilder.Entity("SistemaCitas.Models.Especialidad", b =>
                {
                    b.Property<int>("IdEspecialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEspecialidad"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("IdEspecialidad");

                    b.ToTable("ESPECIALIDAD");

                    b.HasData(
                        new
                        {
                            IdEspecialidad = 1,
                            Activo = true,
                            Nombre = "Medicina General"
                        },
                        new
                        {
                            IdEspecialidad = 2,
                            Activo = true,
                            Nombre = "Pediatria"
                        },
                        new
                        {
                            IdEspecialidad = 3,
                            Activo = true,
                            Nombre = "Ginecologia"
                        },
                        new
                        {
                            IdEspecialidad = 4,
                            Activo = true,
                            Nombre = "Cirugia"
                        });
                });

            modelBuilder.Entity("SistemaCitas.Models.HistorialPuntaje", b =>
                {
                    b.Property<int>("IdHistorialPuntaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorialPuntaje"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCita")
                        .HasColumnType("int");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PuntajeAnterior")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PuntajeNuevo")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RegistradoPorId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdHistorialPuntaje");

                    b.HasIndex("IdCita");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("RegistradoPorId");

                    b.ToTable("HISTORIAL_PUNTAJE");
                });

            modelBuilder.Entity("SistemaCitas.Models.HorarioDoctor", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CuposPorHora")
                        .HasColumnType("int");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdDoctor")
                        .HasColumnType("int");

                    b.HasKey("IdHorario");

                    b.HasIndex("IdDoctor");

                    b.ToTable("HORARIO_DOCTOR");
                });

            modelBuilder.Entity("SistemaCitas.Models.Ipress", b =>
                {
                    b.Property<int>("IdIpress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIpress"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoRenipress")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IdDistrito")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("IdUnidadEjecutora")
                        .HasColumnType("int");

                    b.Property<string>("NivelAtencion")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdIpress");

                    b.HasIndex("CodigoRenipress")
                        .IsUnique();

                    b.HasIndex("IdDistrito");

                    b.HasIndex("IdUnidadEjecutora");

                    b.ToTable("IPRESS");
                });

            modelBuilder.Entity("SistemaCitas.Models.Medicamento", b =>
                {
                    b.Property<int>("IdMedicamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedicamento"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Presentacion")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IdMedicamento");

                    b.ToTable("MEDICAMENTO");
                });

            modelBuilder.Entity("SistemaCitas.Models.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaciente"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdDistrito")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("IdPlanSeguro")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("PorcentajeImportancia")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RegistradoPorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdPaciente");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("IdDistrito");

                    b.HasIndex("IdPlanSeguro");

                    b.HasIndex("RegistradoPorId");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasFilter("[UsuarioId] IS NOT NULL");

                    b.ToTable("PACIENTE");
                });

            modelBuilder.Entity("SistemaCitas.Models.PlanSeguro", b =>
                {
                    b.Property<int>("IdPlanSeguro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlanSeguro"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IdPlanSeguro");

                    b.ToTable("PLAN_SEGURO");

                    b.HasData(
                        new
                        {
                            IdPlanSeguro = 1,
                            Nombre = "SIS Gratuito"
                        },
                        new
                        {
                            IdPlanSeguro = 2,
                            Nombre = "SIS Para Todos"
                        },
                        new
                        {
                            IdPlanSeguro = 3,
                            Nombre = "SIS Independiente"
                        });
                });

            modelBuilder.Entity("SistemaCitas.Models.Provincia", b =>
                {
                    b.Property<string>("IdProvincia")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("IdDepartamento")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IdProvincia");

                    b.HasIndex("IdDepartamento");

                    b.ToTable("PROVINCIA");

                    b.HasData(
                        new
                        {
                            IdProvincia = "1301",
                            IdDepartamento = "13",
                            Nombre = "Trujillo"
                        },
                        new
                        {
                            IdProvincia = "1302",
                            IdDepartamento = "13",
                            Nombre = "Ascope"
                        },
                        new
                        {
                            IdProvincia = "1311",
                            IdDepartamento = "13",
                            Nombre = "Santiago de Chuco"
                        });
                });

            modelBuilder.Entity("SistemaCitas.Models.TipoContrato", b =>
                {
                    b.Property<int>("IdTipoContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoContrato"));

                    b.Property<int>("HorasSemanales")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("IdTipoContrato");

                    b.ToTable("TIPO_CONTRATO");

                    b.HasData(
                        new
                        {
                            IdTipoContrato = 1,
                            HorasSemanales = 12,
                            Nombre = "Honorarios"
                        },
                        new
                        {
                            IdTipoContrato = 2,
                            HorasSemanales = 24,
                            Nombre = "Part time"
                        },
                        new
                        {
                            IdTipoContrato = 3,
                            HorasSemanales = 48,
                            Nombre = "Full day"
                        });
                });

            modelBuilder.Entity("SistemaCitas.Models.Triaje", b =>
                {
                    b.Property<int>("IdTriaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTriaje"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FrecuenciaCardiaca")
                        .HasColumnType("int");

                    b.Property<int>("IdCita")
                        .HasColumnType("int");

                    b.Property<decimal>("PesoKg")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PresionArterial")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("SaturacionO2")
                        .HasColumnType("int");

                    b.Property<decimal>("TallaCm")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TemperaturaC")
                        .HasColumnType("decimal(4,1)");

                    b.HasKey("IdTriaje");

                    b.HasIndex("IdCita")
                        .IsUnique();

                    b.ToTable("TRIAJE");
                });

            modelBuilder.Entity("SistemaCitas.Models.UnidadEjecutora", b =>
                {
                    b.Property<int>("IdUnidadEjecutora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnidadEjecutora"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdUnidadEjecutora");

                    b.ToTable("UNIDAD_EJECUTORA");
                });

            modelBuilder.Entity("SistemaCitas.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("IdIpress")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("IdIpress");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SistemaCitas.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SistemaCitas.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCitas.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SistemaCitas.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaCitas.Models.AtencionDiagnostico", b =>
                {
                    b.HasOne("SistemaCitas.Models.Cie10", "Cie10")
                        .WithMany()
                        .HasForeignKey("CodigoCie10")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCitas.Models.AtencionMedica", "AtencionMedica")
                        .WithMany("Diagnosticos")
                        .HasForeignKey("IdAtencion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AtencionMedica");

                    b.Navigation("Cie10");
                });

            modelBuilder.Entity("SistemaCitas.Models.AtencionMedica", b =>
                {
                    b.HasOne("SistemaCitas.Models.Cita", "Cita")
                        .WithOne("AtencionMedica")
                        .HasForeignKey("SistemaCitas.Models.AtencionMedica", "IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("SistemaCitas.Models.Auditoria", b =>
                {
                    b.HasOne("SistemaCitas.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaCitas.Models.Cita", b =>
                {
                    b.HasOne("SistemaCitas.Models.Doctor", "Doctor")
                        .WithMany("Citas")
                        .HasForeignKey("IdDoctor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCitas.Models.Ipress", "Ipress")
                        .WithMany()
                        .HasForeignKey("IdIpress")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCitas.Models.Paciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Ipress");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("SistemaCitas.Models.DetalleReceta", b =>
                {
                    b.HasOne("SistemaCitas.Models.AtencionMedica", "AtencionMedica")
                        .WithMany("Receta")
                        .HasForeignKey("IdAtencion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaCitas.Models.Medicamento", "Medicamento")
                        .WithMany()
                        .HasForeignKey("IdMedicamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AtencionMedica");

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("SistemaCitas.Models.Distrito", b =>
                {
                    b.HasOne("SistemaCitas.Models.Provincia", "Provincia")
                        .WithMany("Distritos")
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("SistemaCitas.Models.Doctor", b =>
                {
                    b.HasOne("SistemaCitas.Models.Ipress", "Ipress")
                        .WithMany("Doctores")
                        .HasForeignKey("IdIpress")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCitas.Models.TipoContrato", "TipoContrato")
                        .WithMany("Doctores")
                        .HasForeignKey("IdTipoContrato")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCitas.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("SistemaCitas.Models.Doctor", "UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ipress");

                    b.Navigation("TipoContrato");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaCitas.Models.DoctorEspecialidad", b =>
                {
                    b.HasOne("SistemaCitas.Models.Doctor", "Doctor")
                        .WithMany("DoctorEspecialidades")
                        .HasForeignKey("IdDoctor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCitas.Models.Especialidad", "Especialidad")
                        .WithMany("DoctorEspecialidades")
                        .HasForeignKey("IdEspecialidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("SistemaCitas.Models.HistorialPuntaje", b =>
                {
                    b.HasOne("SistemaCitas.Models.Cita", "Cita")
                        .WithMany()
                        .HasForeignKey("IdCita");

                    b.HasOne("SistemaCitas.Models.Paciente", "Paciente")
                        .WithMany("HistorialPuntajes")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCitas.Models.Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId");

                    b.Navigation("Cita");

                    b.Navigation("Paciente");

                    b.Navigation("RegistradoPor");
                });

            modelBuilder.Entity("SistemaCitas.Models.HorarioDoctor", b =>
                {
                    b.HasOne("SistemaCitas.Models.Doctor", "Doctor")
                        .WithMany("Horarios")
                        .HasForeignKey("IdDoctor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("SistemaCitas.Models.Ipress", b =>
                {
                    b.HasOne("SistemaCitas.Models.Distrito", "Distrito")
                        .WithMany()
                        .HasForeignKey("IdDistrito")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCitas.Models.UnidadEjecutora", "UnidadEjecutora")
                        .WithMany("Ipress")
                        .HasForeignKey("IdUnidadEjecutora")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Distrito");

                    b.Navigation("UnidadEjecutora");
                });

            modelBuilder.Entity("SistemaCitas.Models.Paciente", b =>
                {
                    b.HasOne("SistemaCitas.Models.Distrito", "Distrito")
                        .WithMany()
                        .HasForeignKey("IdDistrito")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCitas.Models.PlanSeguro", "PlanSeguro")
                        .WithMany("Pacientes")
                        .HasForeignKey("IdPlanSeguro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaCitas.Models.Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaCitas.Models.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("SistemaCitas.Models.Paciente", "UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Distrito");

                    b.Navigation("PlanSeguro");

                    b.Navigation("RegistradoPor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaCitas.Models.Provincia", b =>
                {
                    b.HasOne("SistemaCitas.Models.Departamento", "Departamento")
                        .WithMany("Provincias")
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("SistemaCitas.Models.Triaje", b =>
                {
                    b.HasOne("SistemaCitas.Models.Cita", "Cita")
                        .WithOne("Triaje")
                        .HasForeignKey("SistemaCitas.Models.Triaje", "IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("SistemaCitas.Models.Usuario", b =>
                {
                    b.HasOne("SistemaCitas.Models.Ipress", "Ipress")
                        .WithMany()
                        .HasForeignKey("IdIpress");

                    b.Navigation("Ipress");
                });

            modelBuilder.Entity("SistemaCitas.Models.AtencionMedica", b =>
                {
                    b.Navigation("Diagnosticos");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("SistemaCitas.Models.Cita", b =>
                {
                    b.Navigation("AtencionMedica");

                    b.Navigation("Triaje");
                });

            modelBuilder.Entity("SistemaCitas.Models.Departamento", b =>
                {
                    b.Navigation("Provincias");
                });

            modelBuilder.Entity("SistemaCitas.Models.Doctor", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("DoctorEspecialidades");

                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("SistemaCitas.Models.Especialidad", b =>
                {
                    b.Navigation("DoctorEspecialidades");
                });

            modelBuilder.Entity("SistemaCitas.Models.Ipress", b =>
                {
                    b.Navigation("Doctores");
                });

            modelBuilder.Entity("SistemaCitas.Models.Paciente", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("HistorialPuntajes");
                });

            modelBuilder.Entity("SistemaCitas.Models.PlanSeguro", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("SistemaCitas.Models.Provincia", b =>
                {
                    b.Navigation("Distritos");
                });

            modelBuilder.Entity("SistemaCitas.Models.TipoContrato", b =>
                {
                    b.Navigation("Doctores");
                });

            modelBuilder.Entity("SistemaCitas.Models.UnidadEjecutora", b =>
                {
                    b.Navigation("Ipress");
                });
#pragma warning restore 612, 618
        }
    }
}
